// ทำไว้เฉยๆ

export const GameConfig = {
    STARTING_MONEY: 1000,
    PASS_START_BONUS: 200,
    JAIL_BAIL_AMOUNT: 250,
    TAKEOVER_MULTIPLIER: 1.5,
    TAKEOVER_LIMIT: 1,
    MAX_PROPERTIES: 5,
    MAX_DIRECT_PURCHASES: 7,
    SELL_RATE: 0.3,
    TAX_RATE: 0.15,
} as const;

export const NORMAL_AI_CONFIG = {
    MIN_CASH_BUFFER_AFTER_BUY: 150,
    GOOD_RENT_THRESHOLD: 30,
    MIN_CASH_BUFFER_AFTER_BAIL: 300,
} as const;

export const HARD_AI_CONFIG = {
    MIN_CASH_RESERVE_AFTER_BUY: 150,
    ROI_THRESHOLD_LEADING: 0,
    ROI_THRESHOLD_BEHIND: -20,
    MIN_CASH_RESERVE_AFTER_BAIL: 100,
    ACTIVE_PORTFOLIO_SIZE: 3,
} as const;

export const CHANCE_CONFIG = {
    FORWARD_STEPS: 5,
    FORWARD_PROBABILITY: 0.20,

    SMALL_BONUS: 100,
    SMALL_BONUS_PROBABILITY: 0.15,

    BILL_AMOUNT: 150,
    BILL_PROBABILITY: 0.20,

    TINY_BONUS: 50,
    TINY_BONUS_PROBABILITY: 0.20,

    LOTTERY_BONUS: 300,
    LOTTERY_PROBABILITY: 0.10,

    BACKWARD_STEPS: -3,
    BACKWARD_PROBABILITY: 0.15,
} as const;

